djangodelights/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('inventory/', include('inventory.urls') ),
]

inventory/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),

    #path("<pk>/details", views.details, name="details"),

    path("menu", views.MenuItemList.as_view(), name="menu"),
    path("menuitem/create", views.MenuItemCreate.as_view(), name="menuitemcreate"),
    path("menuitem/<int:pk>/update", views.MenuItemUpdate.as_view(), name="menuitemupdate"),
    path("menuitem/<int:pk>/delete", views.MenuItemDelete.as_view(), name="menuitemdelete"),

    path("ingredient", views.IngredientList.as_view(), name="ingredient"),
    path("ingredient/create", views.IngredientCreate.as_view(), name="ingredientcreate"),
    path("ingredient/<int:pk>/update", views.IngredientUpdate.as_view(), name="ingredientupdate"),
    path("ingredient/<int:pk>/delete", views.IngredientDelete.as_view(), name="ingredientdelete"),
    path("ingredient/<int:pk>/menuitems", views.IngredientInMenuItems.as_view(), name="ingredientinmenuitems"),

    #path("purchases", views.purchases, name="purchases"),
    path("purchases", views.PurchasesList.as_view(), name="purchases"),
    path("purchases/create", views.PurchasesCreate.as_view(), name="purchasescreate"),
    path("purchases/<int:pk>/update", views.PurchasesUpdate.as_view(), name="purchasesupdate"),
    path("purchases/<int:pk>/delete", views.PurchasesDelete.as_view(), name="purchasesdelete"),
    path("purchases/create/error", views.PurchasesCreateError, name="purchasescreateerror"),
    
    #path("reciperequirement", views.RecipeRequirementList.as_view(), name="reciperequirement"),
    #path("reciperequirement/<int:pk>", views.RecipeRequirementList.as_view(), name="reciperequirement"),
    path("reciperequirement/<int:pk>/", views.RecipeRequirementList.as_view(), name="reciperequirement"),
    path("reciperequirement/create/<int:pk>/", views.RecipeRequirementCreate.as_view(), name="reciperequirementcreate"),
    path("reciperequirement/<int:pk>/update", views.RecipeRequirementUpdate.as_view(), name="reciperequirementupdate"),
    path("reciperequirement/<int:pk>/delete", views.RecipeRequirementDelete.as_view(), name="reciperequirementdelete"),
]

inventory/models.py
from django.db import models

import datetime

from django.core.validators import MinValueValidator

# Create your models here.
class MenuItem(models.Model):
    title = models.CharField(max_length=50, unique=True)
    price = models.FloatField(default=0.0)

    def __str__(self):
        return self.title

class Ingredient(models.Model):
    
    CUP = "CUP"
    OUNCE = "OZS"
    TABLESPOON = "TBS"
    TEASPOON = "TSP"
    GRAM = "GRM"
    BOX = "BOX"
    SMALL = "SML"
    MEDIUM = "MED"
    LARGE = "LRG"
    POUND = "LBS"
    CANNOLI_SHELL = "CNS"

    UNIT_TYPES = [
        (CUP, "Cup"),
        (OUNCE, "Ounce"),
        (TABLESPOON, "Tablespoon"),
        (TEASPOON, "Teaspoon"),
        (BOX, "Box"),
        (GRAM,"Gram"),
        (LARGE,"Large"),
        (MEDIUM,"Medium"),
        (SMALL,"Small"),
        (POUND, "LBS"),
        (CANNOLI_SHELL, "Cannoli Shell"),
    ]

    name = models.CharField(max_length=30, unique=True)
    quantity = models.FloatField(default=0)
    unit = models.CharField(max_length=3, choices=UNIT_TYPES)
    unit_price = models.FloatField(default=0.0)

    def __str__(self):
        return self.name

class RecipeRequirement(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.FloatField(
        default=0.0, 
        validators=[MinValueValidator(.1)]
    )

    class Meta:
        unique_together = ['menu_item', 'ingredient']

    def __str__(self):
        return self.menu_item.title + " - " + self.ingredient.name

class Purchases(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    amount_paid = models.FloatField(default=0.0)
    timestamp = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return self.menu_item.title
         

inventory/forms.py
from django import forms
from .models import MenuItem, Ingredient, RecipeRequirement, Purchases

class MenuItemCreateForm(forms.ModelForm):
    class Meta:
        model = MenuItem 
        fields = "__all__"

class IngredientCreateForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = "__all__"

class PurchasesCreateForm(forms.ModelForm):
    class Meta:
        model = Purchases
        fields = "__all__"

class RecipeRequirementCreateForm(forms.ModelForm):
    class Meta:
        model = RecipeRequirement
        fields = ("ingredient", "quantity")    

inventory/views.py
from django.shortcuts import render, get_object_or_404

from .models import MenuItem, Ingredient, RecipeRequirement, Purchases

from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView

from .forms import MenuItemCreateForm, IngredientCreateForm, PurchasesCreateForm, RecipeRequirementCreateForm

from django.urls import reverse_lazy

from django.forms import formset_factory



# Create your views here.
def home(request):
    return render(request, "inventory/home.html")

def details(request):
    #all_requirements = RecipeRequirement.objects.all()
    #context = {"all_requirements" : all_requirements }
    return render(request, 'inventory/details.html' )


class MenuItemList(ListView):
    model = MenuItem
    template_name = "inventory/menu.html"

class MenuItemCreate(CreateView):
    model = MenuItem
    form_class = MenuItemCreateForm
    template_name = "inventory/add_menuitem.html"

    def get_success_url(self):
        return reverse_lazy('reciperequirementcreate', kwargs={'pk': self.object.pk})


class MenuItemUpdate(UpdateView):
    model = MenuItem
    form_class = MenuItemCreateForm
    success_url = reverse_lazy("menu")
    template_name = "inventory/update_menuitem.html"    

class MenuItemDelete(DeleteView):
    model = MenuItem
    #success_url = reverse_lazy("inventory")
    success_url = "/inventory/menu"
    template_name = "inventory/delete_menuitem.html"




class IngredientList(ListView):
    model = Ingredient
    template_name = "inventory/ingredient.html"

class IngredientCreate(CreateView):
    model = Ingredient
    form_class = IngredientCreateForm
    success_url = reverse_lazy("ingredient")
    template_name = "inventory/add_ingredient.html"

class IngredientUpdate(UpdateView):
    model = Ingredient
    form_class = IngredientCreateForm
    success_url = reverse_lazy("ingredient")
    template_name = "inventory/update_ingredient.html"    

class IngredientDelete(DeleteView):
    model = Ingredient
    #success_url = reverse_lazy("inventory")
    success_url = "/inventory/ingredient"
    template_name = "inventory/delete_ingredient.html"

class IngredientInMenuItems(ListView):
    model = RecipeRequirement
    template_name = "inventory/ingredient_in_menuitems.html"
    context_object_name = 'RR'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        url_pk = self.kwargs['pk']
        title = Ingredient.objects.get(pk=url_pk)

        context['url_pk'] = url_pk
        context['title'] = title

        return context

#def purchases(request):
#   return render(request, "inventory/purchases.html")

class PurchasesList(ListView):
    model = Purchases
    template_name = "inventory/purchases.html"

    #def get_queryset(self):
    #    return Purchases.objects.order_by('-timestamp')[:3]
    
    
from django.http import HttpResponseRedirect 
from django.http import HttpResponse

from django.contrib import messages

class SuccessMessageMixin:
    success_message = ''

    def form_valid(self, form):
        response = super().form_valid(form)
        success_message = self.get_success_message(form.cleaned_data)
        if success_message:
            messages.success(self.request, success_message)

        return response
    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data
        #return super().form_valid(form, request)

class PurchasesCreate(SuccessMessageMixin, CreateView):
    model = Purchases
    form_class = PurchasesCreateForm
    success_url = reverse_lazy("purchases")
    template_name = "inventory/add_purchases.html"

    #success_message = None

    # this will add the amount_paid to the database automatically
    def form_valid(self, form):
        
        menu_item = form.cleaned_data.get('menu_item')
        amount_paid = form.cleaned_data.get('amount_paid')
        menu_item_ID = menu_item.pk
  
        print("QUERY:")
        available_ingredient_qty = 0
        required_ingredient_qty = 0
        tuple_numbers = []

        # update the quantity of each ingredient
        for i in RecipeRequirement.objects.filter(menu_item=menu_item.pk):
            required_ingredient_qty = i.quantity
            for k in Ingredient.objects.filter(id=i.ingredient.pk):
                available_ingredient_qty = k.quantity
           
            print("Required QTY: ", required_ingredient_qty )
            print("Available QTY: ", available_ingredient_qty )

            tuple_numbers.append( [i.ingredient.pk, available_ingredient_qty, required_ingredient_qty] )

        allIngredientsAvailable = True

        for t in tuple_numbers:
            if( (t[1] - t[2]) < 0 or t[1] == 0 ):
                allIngredientsAvailable = False

        if( allIngredientsAvailable == True ):
            for t in tuple_numbers:
                Ingredient.objects.filter(id=t[0]).update(quantity=(t[1]-t[2]))
                print("DEDUCTING INGREDIENTS")

            print("\n\n\n")

            if menu_item and amount_paid <= 0:
                form.instance.amount_paid = menu_item.price

            #success_message = "Purchase Added Successfully!"
            return super().form_valid(form)
        else:
            return HttpResponseRedirect("./create/error")
            #success_message = "Not enough ingredients!"
            #return super().form_valid(form)

    

class PurchasesUpdate(UpdateView):
    model = Purchases
    form_class = PurchasesCreateForm
    success_url = reverse_lazy("purchases")
    template_name = "inventory/update_purchases.html"    


from django.db.models import F 

class PurchasesDelete(DeleteView):
    model = Purchases
    success_url = reverse_lazy("purchases")
    template_name = "inventory/delete_purchases.html"

    def post(self, request, *args, **kwargs):
        #add_back = form.cleaned_data['confirm_checkbox']
        #add_back = self.kwargs.get('confirm_checkbox')
        
        add_back = request.POST.get('add_ingredients_back') == 'checked'

        # add ingredients back if checkbox is checked
        if add_back:
            # Get the purchase object to be deleted
            purchaseToBeDeleted = self.get_object()

            # loop through the ingredients of the Recipe Requirement for the purchase
            for r in RecipeRequirement.objects.filter(menu_item=purchaseToBeDeleted.menu_item_id):
                
                # get the particular ingredient object from that recipe requirement
                ingredient_object = Ingredient.objects.get( pk=r.ingredient.pk ) 

                # add the recipe requirements back into the inventory
                Ingredient.objects.filter(
                    pk=r.ingredient.pk
                ).update(
                    quantity=F('quantity') + r.quantity
                )

        return super().post(request, *args, **kwargs)


def PurchasesCreateError(request):
    return render(request, "inventory/add_purchase_error.html")

"""class RecipeRequirementList(ListView):
    model = RecipeRequirement
    template_name = "inventory/reciperequirement.html"

    print("a;lkdsjf;lksajdf;lksjad;flkjkf;sakssad")

    def details(request):
        #test = get_object_or_404( RecipeRequirement.objects.filter( menu_item=4 ) )
        #print( test )
        #return render(request, 'reciperequirement', {'test':test})
        return RecipeRequirement.objects.filter( menu_item=4 )
"""

from math import ceil

def round_up_to_two_decimal_places(num):
    return ( ceil( num * 100 ) / 100 )


class RecipeRequirementList(ListView):
    model = RecipeRequirement
    template_name = "inventory/reciperequirement.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        menu_item_cost = 0
        menu_item_price = 0

        # Get the PK for the current URL
        url_pk = self.kwargs['pk']

        # Get the name of the menu item
        title = MenuItem.objects.get(pk=url_pk)

        # Add up the cost of all the ingredients
        for r in RecipeRequirement.objects.filter(menu_item=url_pk):
            menu_item_cost += ( r.ingredient.unit_price * r.quantity )

        for m in MenuItem.objects.filter(pk=url_pk):
            menu_item_price = m.price
            break

        # Get cost and price of the menu item
        menu_item_cost = round_up_to_two_decimal_places( menu_item_cost )
        menu_item_price = round_up_to_two_decimal_places( menu_item_price )

        # round the decimals to the nearest two decimal points
        #   and calculate the menu item profite
        menu_item_cost = round( menu_item_cost, 2 )
        menu_item_price = round( menu_item_price, 2 )
        menu_item_profit = round( menu_item_price - menu_item_cost, 2 )

        menu_item_profit_negative = False

        if menu_item_profit < 0:
            menu_item_profit_negative = True
            menu_item_profit *= -1

        context['url_pk'] = url_pk
        context['title'] = title        
        context['ingredients'] = RecipeRequirement.objects.filter(menu_item=url_pk)
        context['menu_item_instance'] = MenuItem.objects.get(pk=url_pk)
        context['menu_item_cost'] = menu_item_cost
        context['menu_item_price'] = menu_item_price
        context['menu_item_profit'] = menu_item_profit
        context['menu_item_profit_negative'] = menu_item_profit_negative
        

        return context



RecipeRequirementFormset = formset_factory(RecipeRequirementCreateForm, extra=5, max_num=5)

class RecipeRequirementCreate(FormView):
    model = RecipeRequirementFormset
    form_class = RecipeRequirementFormset
    template_name = "inventory/add_reciperequirement.html"

    def get_success_url(self):
        return reverse_lazy('reciperequirement', args=[ self.kwargs['pk'] ] )

    def form_valid(self, form):
        formset_data = self.request.POST.get('formset')

inventory/templates/inventory/add_ingredient.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1> Inventory Create</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p}}

    <input type="submit" value="Submit"/>
</form>
{% endblock %}

inventory/templates/inventory/add_purchases.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1> Purchases Create</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p}}

    <input type="submit" value="Submit"/>
</form>


{% endblock %}

inventory/templates/inventory/add_reciperequirement.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1> Recipe Requirement Create</h1>




<form method="post">
    {% csrf_token %}
    
    
    
    <div id="form-container">
        <div>{{ form.as_p }}</div>
        <br>
        <input type="hidden" name="formset" value="">
        <button type="button" id="add-form-button">Add Form</button>
        <button type="submit">Submit</button>
    </div>
  
    
  


    
    <script>
      document.addEventListener('DOMContentLoaded', () => {
        const formContainer = document.getElementById('form-container');
        const addFormButton = document.getElementById('add-form-button');
        let formCount = 0;  // Initial form count
  
        addFormButton.addEventListener('click', () => {
          const formHtml = `
            {{ form.as_p }}
          `;
          const formElement = document.createElement('div');
          formElement.innerHTML = formHtml;
          formContainer.appendChild(formElement);
          formCount++;
        });
      });
    </script>
  
    
  </form>

{% endblock %}

inventory/templates/inventory/delete_ingredient.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1> Inventory Create</h1>

<form action="" method="POST">
    {% csrf_token %}
    <p> Are you sure you want to delete <strong>{{ object }}</strong>? </p>

    <input type="submit" value="Confirm"/>
</form>
{% endblock %}

inventory/templates/inventory/delete_menuitem.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1> Delete Menu Item</h1>

<form action="" method="POST">
    {% csrf_token %}
    <p> Are you sure you want to <span class="font-weight-bold">delete <strong>{{ object }}</strong>? </p>

    <input type="submit" value="Confirm"/>
</form>
{% endblock %}

inventory/templates/inventory/delete_purchases.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1> Purchases Create</h1>

<form action="" method="POST">
    {% csrf_token %}

    <label>
        <input type="checkbox" name="add_ingredients_back" value="checked">
        Add ingredients back to the inventory?
    </label>

    <p> Are you sure you want to delete <strong>{{ object }}</strong>? </p>

    <input type="submit" value="Confirm"/>
</form>
{% endblock %}

inventory/templates/inventory/home.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1 class="text-center"> Homepage </h1>
{% endblock %}

inventory/templates/inventory/ingredient.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1 class="text-center text-muted my-4"> Inventory </h1>

<div class="table-responsive">
    <div class="table-inner-div">
        <table class="table table-striped table-active" >
            <thead class="bg-active">
                <th> ID </th>
                <th> Name </th>
                <th> Quantity </th>
                <th> Unit </th>
                <th> Unit Price </th>
                <th> Edit </th>
                <th> Delete </th>
            </thead>
            {% for ingredient in ingredient_list %}
            <tr>
                <td>{{ ingredient.id }}</td>
                <td> <a href="{% url 'ingredientinmenuitems' ingredient.id %}"> {{ ingredient.name }} </a> </td>
                <td>{{ ingredient.quantity }}</td>
                <td>{{ ingredient.unit }}</td>
                <td>${{ ingredient.unit_price | floatformat:2 }}</td>
                <td> 
                    <a class="btn btn-warning" href="{% url 'ingredientupdate' ingredient.id %}">
                        <img src="/static/wrench.svg">
                    </a> 
                </td>
                <td> 
                    <a class="btn btn-danger" href="{% url 'ingredientdelete' ingredient.id %}">
                        <img src="/static/x-circle.svg">
                    </a> 
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <br><br>
</div> 

<a class="btn shadow-lg  add_btn position-absolute bottom-0" href="{% url 'ingredientcreate' %}">
    ADD Ingredient
</a>

<br><br> 

{% endblock %}

inventory/templates/inventory/ingredient_in_menuitems.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1 class="text-center text-muted my-4"> Ingredient: {{ title }}</h1>

<!--
<h1> {{ view.kwargs.pk }}</h1>
-->


<table class="table table-striped table-active">

<thead class="text-center">
    <th> r.id </th>
    <th> r.menu_item </th>
    <th> r.ingredient.id </th>
    <th> r.ingredient </th>
    <th> r.quantity </th>
    <th> Edit </th>
    <th> Delete </th>

</thead>
{% for r in RR %}
<p> {{ RR.kwargs.pk }}</p>
    {% if r.ingredient.pk == view.kwargs.pk %}
    <tr class="text-center">
        <td>{{ r.id }}</td>
        <!--<td>{{ r.menu_item }}</td>>-->
        <td> <a href="{% url 'reciperequirement' r.menu_item.id %}"> {{ r.menu_item.title }} </a> </td>
        <td>{{ r.ingredient.id }}</td>
        <td>{{ r.ingredient }}</td>
        <td>{{ r.quantity }}</td>
        <td> 
            <a class="btn btn-warning" href="{% url 'menuitemupdate' r.menu_item.pk %}">
                <img src="/static/wrench.svg">
            </a> 
        </td>
        <td> 
            <a class="btn btn-danger" href="{% url 'menuitemdelete' r.menu_item.pk %}">
                <img src="/static/x-circle.svg">
            </a> 
        </td>
    </tr>
    {% endif %}
{% endfor %}
</table>

<br><br>


{% endblock %}

inventory/templates/inventory/menu.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1 class="text-center text-muted my-4"> Menu </h1>

<div class="table-responsive">
    <div class="table-inner-div">
        <table class="table table-striped table-active" >
            <thead>
                <th> PK </th>
                <th> Title </th>
                <th> Price </th>
                <th> Edit </th>
                <th> Delete </th>
            </thead>
            {% for menuitem in menuitem_list %}
            <tr>
                <td> {{ menuitem.id }}</td>
                <td> <a class="link-underline link-underline-opacity-0" href="{% url 'reciperequirement' menuitem.id %}"> {{ menuitem.title }} </a> </td>
                <td>${{ menuitem.price | floatformat:2 }}</td>
                <td> 
                    <a class="btn btn-warning" href="{% url 'menuitemupdate' menuitem.id %}">
                        <img src="/static/wrench.svg">
                    </a> 
                </td>
                <td> 
                    <a class="btn btn-danger" href="{% url 'menuitemdelete' menuitem.id %}">
                        <img src="/static/x-circle.svg">
                    </a> 
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

<br><br>
<a class="btn shadow-lg position-absolute bottom-0" style="background-color: #00e9cc;" href="{% url 'menuitemcreate' %}">
    ADD Menu Item
</a> 

<br><br>


{% endblock %}

inventory/templates/inventory/reciperequirement.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1 class="text-center text-muted my-4"> {{ menu_item_instance.title }} </h1>
<h2 class="text-center text-muted my-4"> Recipe Requirement </h2>


<!-- if r.menu_item.pk == request.resolver_match.kwargs.pk -->

<div class="table-responsive">
    <div class="table-inner-div">
        <table class="table table-striped table-active">
            <thead>
                <th> PK </th>
                <th> Ingredient </th>
                <th> Quantity</th>
                <th> Unit Type </th>
                <th> Unit Price </th>
                <th> RR - ID </th>
                <th> Menu Item Foreign Key</th>
                <th> Ingredient Foreign Key</th>
                <th> Update </th>
                <th> Delete </th>
            </thead>
        
            {% for i in ingredients %}
            <tr>
                <td> <a href="{% url 'ingredientinmenuitems' i.ingredient.pk %}"> {{ i.ingredient.pk }} </a> </td>
                <td> <a href="{% url 'ingredientinmenuitems' i.ingredient.pk %}"> {{ i.ingredient }} </a> </td>
                <td> {{ i.quantity }}</td>
                <td> {{i.ingredient.unit }}</td>
                <td> ${{i.ingredient.unit_price | floatformat:2 }}</td>
                <td> {{i.pk}} </td>
                <td> {{i.menu_item.pk}} </td>
                <td> {{i.ingredient.pk}} </td>
                <td> 
                    <a class="btn btn-warning" href="{% url 'reciperequirementupdate' i.pk %}">
                        <img src="/static/wrench.svg">
                    </a> 
                </td>
                <td> 
                    <a class="btn btn-danger" href="{% url 'reciperequirementdelete' i.pk %}">
                        <img src="/static/x-circle.svg">
                    </a> 
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <br>

    <div class="row">
        <div class="col-md-2 text-right">
            <ul class="list-group text-end">
                <li class="text-end list-group-item list-group-item-secondary">Menu Item Price: ${{menu_item_price}} </li>
                <li class="text-right list-group-item list-group-item-secondary">Menu Item Cost: ${{menu_item_cost}} </li>
                {% if menu_item_profit_negative == True %}
                    <li class="text-right list-group-item list-group-item-secondary">Menu Item Profit: <span class="text-danger">-${{menu_item_profit}}</span> </li>
                {% else %}
                    <li class="text-right list-group-item list-group-item-secondary">Menu Item Profit: ${{menu_item_profit}} </li>
                {% endif %}
                
            </ul>
        </div>
    </div>

    <!--<p> PRimary KEy: {{request.resolver_match.kwargs.pk}}</p>-->
    <br>
    
</div>
    
<div class="row">
    <div class="btn-group">
        <a class="btn shadow-lg d-inline-block" style="background-color: #00e9cc;" href="{% url 'reciperequirementcreate' url_pk %}">
            Add Recipe Requirement for ... {{ menu_item_instance.title }}
        </a> 
        <a class="btn btn-warning d-inline-block" href="{% url 'menuitemupdate' url_pk %}"> Edit </a> 
    
        <a class="btn btn-danger d-inline-block" href="{% url 'menuitemdelete' url_pk %}"> Delete </a> 
    </div>
</div>




<br><br>

{% endblock %}

inventory/templates/inventory/update_menuitem.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1> Menu Item Update</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Update"/>
</form>
{% endblock %}

inventory/templates/inventory/update_purchases.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1> Purchases Update</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Update"/>
</form>
{% endblock %}

inventory/templates/inventory/update_reciperequirement.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Django Delights {% endblock %}

{% block content %}
<h1> RecipeRequirement Update</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Update"/>
</form>
<p> PRimary KEy: {{request.resolver_match.kwargs.pk}}</p>
{% endblock %}